language: cpp
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-all-dev
script: cmake . && make
compiler:
  - clang
  - gcc

env:
  global:
    - secure: "O+BGqz4ugoVIJbQTh0dJjKRrsSVzkCYSe0WpRzEWK3l8Mw7hqX300g81TxRwTzN2zfUsROMzaeGaXWfGzYakgW59K1WIioaczxtv2MzzUQTbqzJPa+qQoP9bk/b2wJ5jcOL965/rudRju4UiIwuIgzDAMN3nAfIEJgV/2zANLIg="
addons:
  coverity_scan:
    project:
      name: "trailofbits/pe-parse"
      description: "Principled, lightweight C/C++ PE parser"
    notification_email: dan@trailofbits.com
    build_command_prepend: "cmake ."
    build_command:   "make"
    branch_pattern: master
