[package]
name = "pe-parse"
version = "0.1.0"
edition = "2021"

[lib]
name = "pe_parse"
crate-type = ["cdylib", "staticlib"]

[dependencies]
libc = "0.2"
object = { version = "0.31.1", features = ["read_core", "pe"] }

[dev-dependencies]
cbindgen = "0.24"
